name: Rendezvous

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Github Checkout
        uses: actions/checkout@v3
        
      # Uses our Docker Hub username and access token to log-in
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      # Setup QEMU for Multiplatform targets
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64         
          
      # Setup Docker Buildx to create the builder instance using a BuildKit container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Build the image and push it to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./screensy-rendezvous/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-rendezvous:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-rendezvous:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-rendez-vous:buildcache,mode=max
